### ISSUE TITLE
Unable to unpack .queries.json.gz

### ISSUE THREAD

**Issue by DLiuhui** [fabgeyer/dataset-networking2019#1]
Excuse that, all the ***.queries.json.gz** archive can't be unpacked, no matter in Ubuntu or Windows OS.
Would you mind checking the data and upload again if data archives truely exists some problems?

**Comment by fabgeyer** [comment]
The dataset is stored in the git repository using [git lfs](https://git-lfs.github.com/). Install git lfs on your system first and then clone the repository using:

```
$ git lfs clone https://github.com/fabgeyer/dataset-networking2019.git
```

The `dataset` folder should be around 170M.
